---
title: "dm-ws-10-01"
author: "Thomas Nauss"
date: "Thursday, January 15, 2015"
output: html_document
---


```{r, echo=FALSE, warning=FALSE, message=FALSE, results="hide"}
inpath <- "active/moc/dm/examples"

dsn <- switch(Sys.info()[["sysname"]], 
              "Linux" = "/media/permanent/",
              "Windows" = "D:/")
setwd(paste0(dsn, inpath))

library(rgdal)
library(raster)
library(sp)
library(RColorBrewer)
library(latticeExtra)

vegetation <- readOGR("data_procd/spatial_data/data_2014_subset1.shp", 
                 "data_2014_subset1")
landsat <- raster("data_procd/spatial_data/LC82100502014328LGN00_B3.tif")
vegetation <- spTransform(vegetation, CRS(projection(landsat)))
```


#### Function for plotting maps
Some description of the function...
```{r}
map <- function(raster, vector, vector_colors="default",
                gnbr=5, attr=3){
  vector_classes <- cut(vector@data[,attr], 6)
  
  if(vector_colors == "default"){
    vector_colors <- colorRampPalette(brewer.pal(6,"Greens"))(6)
  }
  
  min <- max(mean(getValues(raster)) - sd(getValues(raster)), 0)
  max <- mean(getValues(raster)) + sd(getValues(raster))
  
  breaks <- seq(min, max, length.out = 256)
  
  yat = seq(extent(raster)@ymin, 
            extent(raster)@ymax, length.out = gnbr)
  xat = seq(extent(raster)@xmin, 
            extent(raster)@xmax, length.out = gnbr)
  
  plt <- spplot(raster, col.regions = gray.colors(256), at = breaks,
                key = list(space = 'left', text = list(levels(vector_classes)), 
                           points = list(pch = 21, cex = 2, fill = vector_colors)),
                colorkey=list(space="right"),
                panel = function(...){
                  panel.levelplot(...)
                  panel.abline(h = yat, v = xat, col = "grey0", lwd = 0.8, lty = 3) 
                },
                scales = list(x = list(at = xat),
                              y = list(at = yat)))
  
  orl <- spplot(vector, zcol = "COVRG", col.regions = vector_colors)
  
  plt + as.layer(orl)
}

vc <- colorRampPalette(brewer.pal(6,"Blues"))(6)
```


#### Function call
Calling the above function is simple:
```{r}
map(landsat, vegetation, gnbr=3, attr=4)
```



